export const STYLES_LIST = [
  { name: 'Cyberpunk', prompt: 'Cyberpunk aesthetic, neon colors, futuristic, high tech' },
  { name: 'Studio Ghibli', prompt: 'Studio Ghibli style, hand-drawn animation, whimsical' },
  { name: 'Hyper-Realistic Portrait', prompt: 'Hyper-realistic portrait, professional, detailed skin' },
  { name: 'Film Noir', prompt: 'Film noir style, black and white, dramatic lighting' },
  { name: 'Watercolor', prompt: 'Watercolor painting style, soft colors, artistic' },
  { name: 'Fashion Editorial', prompt: 'Fashion editorial photography, professional, stylish' },
  { name: 'Oil Painting', prompt: 'Oil painting style, classical, museum quality' },
  { name: 'Anime', prompt: 'Anime style, vibrant colors, expressive' },
  { name: 'Renaissance Portrait', prompt: 'Renaissance portrait, classical art, elegant' },
  { name: 'Sketch', prompt: 'Detailed pencil sketch, black and white, artistic' },
  { name: 'Pop Art', prompt: 'Pop art style, bold colors, high contrast' },
  { name: 'Vintage Film', prompt: 'Vintage film photography, retro colors, nostalgic' },
  { name: 'Street Photography', prompt: 'Street photography, candid, natural light' },
  { name: 'Black & White', prompt: 'Black and white photography, high contrast, dramatic' },
  { name: 'Manga', prompt: 'Manga style, comic book art, bold lines' },
  { name: 'Photography Studio', prompt: 'Professional studio photography, perfect lighting' },
  { name: 'Charcoal Drawing', prompt: 'Charcoal drawing, expressive, monochromatic' },
  { name: 'Pastel Art', prompt: 'Pastel art, soft colors, delicate' },
  { name: 'Steampunk', prompt: 'Steampunk aesthetic, Victorian, mechanical' },
  { name: 'Art Deco', prompt: 'Art Deco style, geometric, luxurious' },
  { name: 'Impressionist', prompt: 'Impressionist painting, soft focus, dreamy' },
  { name: 'Comic Book', prompt: 'Comic book style, bright colors, bold outlines' },
  { name: 'Desert Photography', prompt: 'Desert landscape photography, golden hour' },
  { name: 'Fantasy Art', prompt: 'Fantasy art, magical, otherworldly' },
  { name: 'Photography Portrait', prompt: 'Professional photography portrait, natural' },
  { name: 'Glass Art', prompt: 'Glass art aesthetic, transparent, crystalline' },
  { name: 'Photorealistic Rendering', prompt: 'Photorealistic 3D rendering, perfect details' },
  { name: 'Graffiti Street Art', prompt: 'Street graffiti art, urban, vibrant' },
  { name: 'Sculpture', prompt: 'Marble sculpture aesthetic, classical, monumental' },
  { name: 'Retro Gaming', prompt: 'Retro video game aesthetic, pixel art, 8-bit' },
  { name: 'Nature Documentary', prompt: 'Nature documentary photography, wildlife' },
  { name: 'Horror Art', prompt: 'Horror art style, dark, atmospheric' },
  { name: 'Romantic Painting', prompt: 'Romantic era painting, emotional, dramatic' },
  { name: 'Surrealism', prompt: 'Surrealism art, dreamlike, abstract' },
  { name: 'Photography Vintage', prompt: 'Vintage photograph aesthetic, aged, nostalgic' },
  { name: 'CGI 3D Character', prompt: 'CGI 3D character, professional rendering' },
  { name: 'Advertising Photography', prompt: 'Commercial advertising photography, professional' },
  { name: 'Travel Photography', prompt: 'Travel photography, exotic locations, vibrant' },
  { name: 'Documentary', prompt: 'Documentary photography, journalistic, authentic' },
  { name: 'Architecture Photography', prompt: 'Architecture photography, geometric, professional' },
  { name: 'Food Photography', prompt: 'Food photography, professional styling, appetizing' },
  { name: 'Wedding Photography', prompt: 'Wedding photography, romantic, elegant' },
  { name: 'Sports Photography', prompt: 'Sports photography, dynamic, action-packed' },
  { name: 'Wildlife Photography', prompt: 'Wildlife photography, nature, majestic' },
  { name: 'Underwater Photography', prompt: 'Underwater photography, ocean, ethereal' },
  { name: 'Night Photography', prompt: 'Night photography, city lights, moody' },
  { name: 'Macro Photography', prompt: 'Macro photography, extreme detail, scientific' },
  { name: 'Drone Photography', prompt: 'Drone photography, aerial view, landscape' },
  { name: 'Golden Hour', prompt: 'Golden hour photography, sunset, warm light' },
  { name: 'Studio Lighting', prompt: 'Studio lighting, professional, controlled' },
]
